name: Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          check-latest: true

      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: ~/.local/share/pnpm/store
          key: ${{ runner.os }}-pnpm7-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Setup dependencies
        run: cd frontend-src && corepack pnpm install

      - name: Run build
        run: cd frontend-src && corepack pnpm run build

      - name: To static
        run: pwd && rm -rf ./static && mv ./frontend-src/build ./static && ls -alh && cat ./static/version

      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: juzisang/ai-pixiv
          flavor: |
            latest=true
          tags: |
            type=semver,pattern={{raw}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
